services:
  jenkins:
    container_name: jenkins-lab-updated
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30000:8080"
      - "50003:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # Add kubectl config
      - /root/.kube:/root/.kube

volumes:
  jenkins_home:
    
      